# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec34b823427c99ce0b075bb680f09558325b83d2e910e5ff63c1e639f2807d1c46ce37176aa88fd4d09c9775d311b8dabe2e160339eaa38ad365928d02451109

test:
  secret_key_base: 27e80cc6240dd85e65cc36385d86e39d0d1ad225b5d6f9fc7c34a6e651c5ec425ef74b0e54e9ed48bd09aea1c7cd392d7ae37a453716055258b01de54dc0e349

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
